.travis.yml, build/.travis.settings.xml, build/bintraySync.sh, build/publish-javadoc.sh, build/sync2MC.sh, pom.xml
=> feat(build): added deployment steps

.travis.yml
=> feat(build): code to sync bintray and maven central repo

pom.xml
=> feat(build): updated pom.xml for syncing bintray and mvn central

pom.xml
=> fix(sync): updated pom.xml

pom.xml
=> fix(build): updated pom.xml

pom.xml
=> fix: dummy commit for fixing build issue in merge 0.10.0

modules/dns-svcs/src/test/java/com/ibm/cloud/networking/dns_svcs/v1/DnsSvcsIT.java
=> feat(private dns): private dns java sdk release commit

modules/coverage-reports/pom.xml, pom.xml
=> feat(private dns): release commit, fix for pom.xml

modules/dns-svcs/src/test/java/com/ibm/cloud/networking/dns_svcs/v1/DnsSvcsIT.java
=> location added

modules/transit-gateway-apis/src/main/java/com/ibm/cloud/networking/transit_gateway_apis/v1/model/CreateTransitGatewayConnectionOptions.java, modules/transit-gateway-apis/src/main/java/com/ibm/cloud/networking/transit_gateway_apis/v1/model/TransitConnection.java, modules/transit-gateway-apis/src/main/java/com/ibm/cloud/networking/transit_gateway_apis/v1/model/TransitGatewayConnectionCust.java
Support for directlink type transit gateway connections
Please make sure that your PR fulfills the following requirements:  
- [X ] Feature
- [X ] No
=> feat: Support for directlink type connections

pom.xml
Increase timeout for nexus-staging plugin
Please make sure that your PR fulfills the following requirements:  
- [ X] Build/CI related changes
- [ X] No
=> fix: Increase nexus-staging timeout

checkstyle.xml, modules/zones-settings/src/main/java/com/ibm/cloud/networking/zones_settings/v1/ZonesSettings.java, modules/zones-settings/src/main/java/com/ibm/cloud/networking/zones_settings/v1/model/GetHttp3Options.java, modules/zones-settings/src/main/java/com/ibm/cloud/networking/zones_settings/v1/model/Http3Resp.java, modules/zones-settings/src/main/java/com/ibm/cloud/networking/zones_settings/v1/model/Http3RespResult.java, modules/zones-settings/src/main/java/com/ibm/cloud/networking/zones_settings/v1/model/UpdateHttp3Options.java, modules/zones-settings/src/test/java/com/ibm/cloud/networking/zones_settings/v1/ZonesSettingsIT.java, modules/zones-settings/src/test/java/com/ibm/cloud/networking/zones_settings/v1/ZonesSettingsTest.java, modules/zones-settings/src/test/java/com/ibm/cloud/networking/zones_settings/v1/model/GetHttp3OptionsTest.java, modules/zones-settings/src/test/java/com/ibm/cloud/networking/zones_settings/v1/model/Http3RespResultTest.java, modules/zones-settings/src/test/java/com/ibm/cloud/networking/zones_settings/v1/model/Http3RespTest.java, modules/zones-settings/src/test/java/com/ibm/cloud/networking/zones_settings/v1/model/UpdateHttp3OptionsTest.java
=> feat(http3): added http3 setting

.secrets.baseline
=> chore: updated .secrets.baseline

.secrets.baseline
=> chore: removed secrets for firewallRules

modules/coverage-reports/pom.xml, modules/webhooks/pom.xml, modules/webhooks/src/main/java/com/ibm/cloud/networking/webhooks/v1/Webhooks.java, modules/webhooks/src/main/java/com/ibm/cloud/networking/webhooks/v1/model/CreateAlertWebhookOptions.java, modules/webhooks/src/main/java/com/ibm/cloud/networking/webhooks/v1/model/DeleteWebhookOptions.java, modules/webhooks/src/main/java/com/ibm/cloud/networking/webhooks/v1/model/GetAlertWebhookResp.java, modules/webhooks/src/main/java/com/ibm/cloud/networking/webhooks/v1/model/GetAlertWebhookRespResult.java, modules/webhooks/src/main/java/com/ibm/cloud/networking/webhooks/v1/model/GetWebhookOptions.java, modules/webhooks/src/main/java/com/ibm/cloud/networking/webhooks/v1/model/ListAlertWebhooksResp.java, modules/webhooks/src/main/java/com/ibm/cloud/networking/webhooks/v1/model/ListAlertWebhooksRespResultItem.java, modules/webhooks/src/main/java/com/ibm/cloud/networking/webhooks/v1/model/ListWebhooksOptions.java, modules/webhooks/src/main/java/com/ibm/cloud/networking/webhooks/v1/model/UpdateAlertWebhookOptions.java, modules/webhooks/src/main/java/com/ibm/cloud/networking/webhooks/v1/model/WebhookSuccessResp.java, modules/webhooks/src/main/java/com/ibm/cloud/networking/webhooks/v1/model/WebhookSuccessRespResult.java, modules/webhooks/src/main/java/com/ibm/cloud/networking/webhooks/v1/package-info.java, modules/webhooks/src/test/java/com/ibm/cloud/networking/webhooks/v1/WebhooksIT.java, modules/webhooks/src/test/java/com/ibm/cloud/networking/webhooks/v1/WebhooksTest.java, modules/webhooks/src/test/java/com/ibm/cloud/networking/webhooks/v1/model/CreateAlertWebhookOptionsTest.java, modules/webhooks/src/test/java/com/ibm/cloud/networking/webhooks/v1/model/DeleteWebhookOptionsTest.java, modules/webhooks/src/test/java/com/ibm/cloud/networking/webhooks/v1/model/GetAlertWebhookRespResultTest.java, modules/webhooks/src/test/java/com/ibm/cloud/networking/webhooks/v1/model/GetAlertWebhookRespTest.java, modules/webhooks/src/test/java/com/ibm/cloud/networking/webhooks/v1/model/GetWebhookOptionsTest.java, modules/webhooks/src/test/java/com/ibm/cloud/networking/webhooks/v1/model/ListAlertWebhooksRespResultItemTest.java, modules/webhooks/src/test/java/com/ibm/cloud/networking/webhooks/v1/model/ListAlertWebhooksRespTest.java, modules/webhooks/src/test/java/com/ibm/cloud/networking/webhooks/v1/model/ListWebhooksOptionsTest.java, modules/webhooks/src/test/java/com/ibm/cloud/networking/webhooks/v1/model/UpdateAlertWebhookOptionsTest.java, modules/webhooks/src/test/java/com/ibm/cloud/networking/webhooks/v1/model/WebhookSuccessRespResultTest.java, modules/webhooks/src/test/java/com/ibm/cloud/networking/webhooks/v1/model/WebhookSuccessRespTest.java, modules/webhooks/src/test/java/com/ibm/cloud/networking/webhooks/v1/utils/TestUtilities.java, pom.xml
=> feat(Webhooks): Added Webhooks

pom.xml
Signed-off-by: Joseph Kalandarishvili <jkalanda@Josephs-MBP.hsd1.mn.comcast.net>
=> fix: updating a dependency version number

package-lock.json, package.json
**Fixes:** fixing the semver vulnerability issue by updating the version number. 
link: https://github.com/IBM/networking-java-sdk/security/dependabot/5
=> chore: updated dependency versions

package-lock.json, package.json
**Fixes:** fixing the semver vulnerability issue by updating the version number. 
link: https://github.com/IBM/networking-java-sdk/security/dependabot/5
=> chore: updated semver version

.travis.yml
Fixing Semantic-release failure 
**Fixes:** 
https://app.travis-ci.com/github/IBM/networking-java-sdk/jobs/622908556 
=> fix: fixing semantic-release failure

package-lock.json
=> fix: updating a vulnerable pakcage to the latest version number
